// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'media_stream.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MediaStream _$MediaStreamFromJson(Map<String, dynamic> json) => MediaStream(
      codec: json['Codec'] as String?,
      codecTag: json['CodecTag'] as String?,
      language: json['Language'] as String?,
      colorTransfer: json['ColorTransfer'] as String?,
      colorPrimaries: json['ColorPrimaries'] as String?,
      colorSpace: json['ColorSpace'] as String?,
      comment: json['Comment'] as String?,
      timeBase: json['TimeBase'] as String?,
      codecTimeBase: json['CodecTimeBase'] as String?,
      title: json['Title'] as String?,
      extradata: json['Extradata'] as String?,
      videoRange: json['VideoRange'] as String?,
      displayTitle: json['DisplayTitle'] as String?,
      displayLanguage: json['DisplayLanguage'] as String?,
      nalLengthSize: json['NalLengthSize'] as String?,
      isInterlaced: json['IsInterlaced'] as bool?,
      isAvc: json['IsAVC'] as bool?,
      channelLayout: json['ChannelLayout'] as String?,
      bitRate: (json['BitRate'] as num?)?.toInt(),
      bitDepth: (json['BitDepth'] as num?)?.toInt(),
      refFrames: (json['RefFrames'] as num?)?.toInt(),
      packetLength: (json['PacketLength'] as num?)?.toInt(),
      channels: (json['Channels'] as num?)?.toInt(),
      sampleRate: (json['SampleRate'] as num?)?.toInt(),
      isDefault: json['IsDefault'] as bool?,
      isForced: json['IsForced'] as bool?,
      height: (json['Height'] as num?)?.toInt(),
      width: (json['Width'] as num?)?.toInt(),
      averageFrameRate: (json['AverageFrameRate'] as num?)?.toInt(),
      realFrameRate: (json['RealFrameRate'] as num?)?.toInt(),
      profile: json['Profile'] as String?,
      type: json['Type'] as String?,
      aspectRatio: json['AspectRatio'] as String?,
      index: (json['Index'] as num?)?.toInt(),
      score: (json['Score'] as num?)?.toInt(),
      isExternal: json['IsExternal'] as bool?,
      deliveryMethod: json['DeliveryMethod'] as String?,
      deliveryUrl: json['DeliveryUrl'] as String?,
      isExternalUrl: json['IsExternalUrl'] as bool?,
      isTextSubtitleStream: json['IsTextSubtitleStream'] as bool?,
      supportsExternalStream: json['SupportsExternalStream'] as bool?,
      path: json['Path'] as String?,
      pixelFormat: json['PixelFormat'] as String?,
      level: (json['Level'] as num?)?.toInt(),
      isAnamorphic: json['IsAnamorphic'] as bool?,
    );

Map<String, dynamic> _$MediaStreamToJson(MediaStream instance) =>
    <String, dynamic>{
      'Codec': instance.codec,
      'CodecTag': instance.codecTag,
      'Language': instance.language,
      'ColorTransfer': instance.colorTransfer,
      'ColorPrimaries': instance.colorPrimaries,
      'ColorSpace': instance.colorSpace,
      'Comment': instance.comment,
      'TimeBase': instance.timeBase,
      'CodecTimeBase': instance.codecTimeBase,
      'Title': instance.title,
      'Extradata': instance.extradata,
      'VideoRange': instance.videoRange,
      'DisplayTitle': instance.displayTitle,
      'DisplayLanguage': instance.displayLanguage,
      'NalLengthSize': instance.nalLengthSize,
      'IsInterlaced': instance.isInterlaced,
      'IsAVC': instance.isAvc,
      'ChannelLayout': instance.channelLayout,
      'BitRate': instance.bitRate,
      'BitDepth': instance.bitDepth,
      'RefFrames': instance.refFrames,
      'PacketLength': instance.packetLength,
      'Channels': instance.channels,
      'SampleRate': instance.sampleRate,
      'IsDefault': instance.isDefault,
      'IsForced': instance.isForced,
      'Height': instance.height,
      'Width': instance.width,
      'AverageFrameRate': instance.averageFrameRate,
      'RealFrameRate': instance.realFrameRate,
      'Profile': instance.profile,
      'Type': instance.type,
      'AspectRatio': instance.aspectRatio,
      'Index': instance.index,
      'Score': instance.score,
      'IsExternal': instance.isExternal,
      'DeliveryMethod': instance.deliveryMethod,
      'DeliveryUrl': instance.deliveryUrl,
      'IsExternalUrl': instance.isExternalUrl,
      'IsTextSubtitleStream': instance.isTextSubtitleStream,
      'SupportsExternalStream': instance.supportsExternalStream,
      'Path': instance.path,
      'PixelFormat': instance.pixelFormat,
      'Level': instance.level,
      'IsAnamorphic': instance.isAnamorphic,
    };
